/// Country dial-code helpers for registration phone numbers.
class CountryDial {
  const CountryDial({
    required this.name,
    required this.iso2,
    required this.dialCode,
    this.nationalNumberLength = const [7, 8, 9, 10, 11, 12, 13, 14, 15],
  });

  final String name;
  final String iso2;
  final String dialCode;
  final List<int> nationalNumberLength;

  String get label => '$name (+$dialCode)';

  /// Builds E.164-style number: +{dial}{national} (national leading 0 stripped).
  String formatPhone(String nationalRaw) {
    var digits = nationalRaw.replaceAll(RegExp(r'\D'), '');
    if (digits.startsWith('0')) {
      digits = digits.substring(1);
    }
    if (digits.startsWith(dialCode)) {
      digits = digits.substring(dialCode.length);
    }
    return '+$dialCode$digits';
  }

  String? validateNational(String? value) {
    if (value == null || value.trim().isEmpty) {
      return 'Phone number is required';
    }
    var digits = value.replaceAll(RegExp(r'\D'), '');
    if (digits.startsWith('0')) digits = digits.substring(1);
    if (digits.startsWith(dialCode)) digits = digits.substring(dialCode.length);
    if (!nationalNumberLength.contains(digits.length)) {
      return 'Enter a valid $name phone number';
    }
    return null;
  }
}

/// All countries / territories with ITU dial codes (Nigeria first — primary market).
const List<CountryDial> kRegistrationCountries = [
  CountryDial(name: 'Nigeria', iso2: 'NG', dialCode: '234', nationalNumberLength: [10]),
  CountryDial(name: 'Afghanistan', iso2: 'AF', dialCode: '93'),
  CountryDial(name: 'Albania', iso2: 'AL', dialCode: '355'),
  CountryDial(name: 'Algeria', iso2: 'DZ', dialCode: '213'),
  CountryDial(name: 'American Samoa', iso2: 'AS', dialCode: '1684'),
  CountryDial(name: 'Andorra', iso2: 'AD', dialCode: '376'),
  CountryDial(name: 'Angola', iso2: 'AO', dialCode: '244'),
  CountryDial(name: 'Anguilla', iso2: 'AI', dialCode: '1264'),
  CountryDial(name: 'Antigua and Barbuda', iso2: 'AG', dialCode: '1268'),
  CountryDial(name: 'Argentina', iso2: 'AR', dialCode: '54'),
  CountryDial(name: 'Armenia', iso2: 'AM', dialCode: '374'),
  CountryDial(name: 'Aruba', iso2: 'AW', dialCode: '297'),
  CountryDial(name: 'Australia', iso2: 'AU', dialCode: '61', nationalNumberLength: [9]),
  CountryDial(name: 'Austria', iso2: 'AT', dialCode: '43'),
  CountryDial(name: 'Azerbaijan', iso2: 'AZ', dialCode: '994'),
  CountryDial(name: 'Bahamas', iso2: 'BS', dialCode: '1242'),
  CountryDial(name: 'Bahrain', iso2: 'BH', dialCode: '973'),
  CountryDial(name: 'Bangladesh', iso2: 'BD', dialCode: '880'),
  CountryDial(name: 'Barbados', iso2: 'BB', dialCode: '1246'),
  CountryDial(name: 'Belarus', iso2: 'BY', dialCode: '375'),
  CountryDial(name: 'Belgium', iso2: 'BE', dialCode: '32'),
  CountryDial(name: 'Belize', iso2: 'BZ', dialCode: '501'),
  CountryDial(name: 'Benin', iso2: 'BJ', dialCode: '229'),
  CountryDial(name: 'Bermuda', iso2: 'BM', dialCode: '1441'),
  CountryDial(name: 'Bhutan', iso2: 'BT', dialCode: '975'),
  CountryDial(name: 'Bolivia', iso2: 'BO', dialCode: '591'),
  CountryDial(name: 'Bosnia and Herzegovina', iso2: 'BA', dialCode: '387'),
  CountryDial(name: 'Botswana', iso2: 'BW', dialCode: '267'),
  CountryDial(name: 'Brazil', iso2: 'BR', dialCode: '55', nationalNumberLength: [10, 11]),
  CountryDial(name: 'British Virgin Islands', iso2: 'VG', dialCode: '1284'),
  CountryDial(name: 'Brunei', iso2: 'BN', dialCode: '673'),
  CountryDial(name: 'Bulgaria', iso2: 'BG', dialCode: '359'),
  CountryDial(name: 'Burkina Faso', iso2: 'BF', dialCode: '226'),
  CountryDial(name: 'Burundi', iso2: 'BI', dialCode: '257'),
  CountryDial(name: 'Cambodia', iso2: 'KH', dialCode: '855'),
  CountryDial(name: 'Cameroon', iso2: 'CM', dialCode: '237'),
  CountryDial(name: 'Canada', iso2: 'CA', dialCode: '1', nationalNumberLength: [10]),
  CountryDial(name: 'Cape Verde', iso2: 'CV', dialCode: '238'),
  CountryDial(name: 'Cayman Islands', iso2: 'KY', dialCode: '1345'),
  CountryDial(name: 'Central African Republic', iso2: 'CF', dialCode: '236'),
  CountryDial(name: 'Chad', iso2: 'TD', dialCode: '235'),
  CountryDial(name: 'Chile', iso2: 'CL', dialCode: '56'),
  CountryDial(name: 'China', iso2: 'CN', dialCode: '86'),
  CountryDial(name: 'Colombia', iso2: 'CO', dialCode: '57'),
  CountryDial(name: 'Comoros', iso2: 'KM', dialCode: '269'),
  CountryDial(name: 'Congo', iso2: 'CG', dialCode: '242'),
  CountryDial(name: 'Cook Islands', iso2: 'CK', dialCode: '682'),
  CountryDial(name: 'Costa Rica', iso2: 'CR', dialCode: '506'),
  CountryDial(name: 'Croatia', iso2: 'HR', dialCode: '385'),
  CountryDial(name: 'Cuba', iso2: 'CU', dialCode: '53'),
  CountryDial(name: 'Curaçao', iso2: 'CW', dialCode: '599'),
  CountryDial(name: 'Cyprus', iso2: 'CY', dialCode: '357'),
  CountryDial(name: 'Czech Republic', iso2: 'CZ', dialCode: '420'),
  CountryDial(name: 'Democratic Republic of the Congo', iso2: 'CD', dialCode: '243'),
  CountryDial(name: 'Denmark', iso2: 'DK', dialCode: '45'),
  CountryDial(name: 'Djibouti', iso2: 'DJ', dialCode: '253'),
  CountryDial(name: 'Dominica', iso2: 'DM', dialCode: '1767'),
  CountryDial(name: 'Dominican Republic', iso2: 'DO', dialCode: '1809'),
  CountryDial(name: 'Ecuador', iso2: 'EC', dialCode: '593'),
  CountryDial(name: 'Egypt', iso2: 'EG', dialCode: '20', nationalNumberLength: [10]),
  CountryDial(name: 'El Salvador', iso2: 'SV', dialCode: '503'),
  CountryDial(name: 'Equatorial Guinea', iso2: 'GQ', dialCode: '240'),
  CountryDial(name: 'Eritrea', iso2: 'ER', dialCode: '291'),
  CountryDial(name: 'Estonia', iso2: 'EE', dialCode: '372'),
  CountryDial(name: 'Eswatini', iso2: 'SZ', dialCode: '268'),
  CountryDial(name: 'Ethiopia', iso2: 'ET', dialCode: '251'),
  CountryDial(name: 'Falkland Islands', iso2: 'FK', dialCode: '500'),
  CountryDial(name: 'Faroe Islands', iso2: 'FO', dialCode: '298'),
  CountryDial(name: 'Fiji', iso2: 'FJ', dialCode: '679'),
  CountryDial(name: 'Finland', iso2: 'FI', dialCode: '358'),
  CountryDial(name: 'France', iso2: 'FR', dialCode: '33', nationalNumberLength: [9]),
  CountryDial(name: 'French Guiana', iso2: 'GF', dialCode: '594'),
  CountryDial(name: 'French Polynesia', iso2: 'PF', dialCode: '689'),
  CountryDial(name: 'Gabon', iso2: 'GA', dialCode: '241'),
  CountryDial(name: 'Gambia', iso2: 'GM', dialCode: '220'),
  CountryDial(name: 'Georgia', iso2: 'GE', dialCode: '995'),
  CountryDial(name: 'Germany', iso2: 'DE', dialCode: '49', nationalNumberLength: [10, 11]),
  CountryDial(name: 'Ghana', iso2: 'GH', dialCode: '233', nationalNumberLength: [9]),
  CountryDial(name: 'Gibraltar', iso2: 'GI', dialCode: '350'),
  CountryDial(name: 'Greece', iso2: 'GR', dialCode: '30'),
  CountryDial(name: 'Greenland', iso2: 'GL', dialCode: '299'),
  CountryDial(name: 'Grenada', iso2: 'GD', dialCode: '1473'),
  CountryDial(name: 'Guadeloupe', iso2: 'GP', dialCode: '590'),
  CountryDial(name: 'Guam', iso2: 'GU', dialCode: '1671'),
  CountryDial(name: 'Guatemala', iso2: 'GT', dialCode: '502'),
  CountryDial(name: 'Guernsey', iso2: 'GG', dialCode: '44'),
  CountryDial(name: 'Guinea', iso2: 'GN', dialCode: '224'),
  CountryDial(name: 'Guinea-Bissau', iso2: 'GW', dialCode: '245'),
  CountryDial(name: 'Guyana', iso2: 'GY', dialCode: '592'),
  CountryDial(name: 'Haiti', iso2: 'HT', dialCode: '509'),
  CountryDial(name: 'Honduras', iso2: 'HN', dialCode: '504'),
  CountryDial(name: 'Hong Kong', iso2: 'HK', dialCode: '852'),
  CountryDial(name: 'Hungary', iso2: 'HU', dialCode: '36'),
  CountryDial(name: 'Iceland', iso2: 'IS', dialCode: '354'),
  CountryDial(name: 'India', iso2: 'IN', dialCode: '91', nationalNumberLength: [10]),
  CountryDial(name: 'Indonesia', iso2: 'ID', dialCode: '62'),
  CountryDial(name: 'Iran', iso2: 'IR', dialCode: '98'),
  CountryDial(name: 'Iraq', iso2: 'IQ', dialCode: '964'),
  CountryDial(name: 'Ireland', iso2: 'IE', dialCode: '353', nationalNumberLength: [9]),
  CountryDial(name: 'Isle of Man', iso2: 'IM', dialCode: '44'),
  CountryDial(name: 'Israel', iso2: 'IL', dialCode: '972'),
  CountryDial(name: 'Italy', iso2: 'IT', dialCode: '39'),
  CountryDial(name: 'Ivory Coast', iso2: 'CI', dialCode: '225'),
  CountryDial(name: 'Jamaica', iso2: 'JM', dialCode: '1876'),
  CountryDial(name: 'Japan', iso2: 'JP', dialCode: '81'),
  CountryDial(name: 'Jersey', iso2: 'JE', dialCode: '44'),
  CountryDial(name: 'Jordan', iso2: 'JO', dialCode: '962'),
  CountryDial(name: 'Kazakhstan', iso2: 'KZ', dialCode: '7'),
  CountryDial(name: 'Kenya', iso2: 'KE', dialCode: '254', nationalNumberLength: [9]),
  CountryDial(name: 'Kiribati', iso2: 'KI', dialCode: '686'),
  CountryDial(name: 'Kosovo', iso2: 'XK', dialCode: '383'),
  CountryDial(name: 'Kuwait', iso2: 'KW', dialCode: '965'),
  CountryDial(name: 'Kyrgyzstan', iso2: 'KG', dialCode: '996'),
  CountryDial(name: 'Laos', iso2: 'LA', dialCode: '856'),
  CountryDial(name: 'Latvia', iso2: 'LV', dialCode: '371'),
  CountryDial(name: 'Lebanon', iso2: 'LB', dialCode: '961'),
  CountryDial(name: 'Lesotho', iso2: 'LS', dialCode: '266'),
  CountryDial(name: 'Liberia', iso2: 'LR', dialCode: '231'),
  CountryDial(name: 'Libya', iso2: 'LY', dialCode: '218'),
  CountryDial(name: 'Liechtenstein', iso2: 'LI', dialCode: '423'),
  CountryDial(name: 'Lithuania', iso2: 'LT', dialCode: '370'),
  CountryDial(name: 'Luxembourg', iso2: 'LU', dialCode: '352'),
  CountryDial(name: 'Macau', iso2: 'MO', dialCode: '853'),
  CountryDial(name: 'Madagascar', iso2: 'MG', dialCode: '261'),
  CountryDial(name: 'Malawi', iso2: 'MW', dialCode: '265'),
  CountryDial(name: 'Malaysia', iso2: 'MY', dialCode: '60'),
  CountryDial(name: 'Maldives', iso2: 'MV', dialCode: '960'),
  CountryDial(name: 'Mali', iso2: 'ML', dialCode: '223'),
  CountryDial(name: 'Malta', iso2: 'MT', dialCode: '356'),
  CountryDial(name: 'Marshall Islands', iso2: 'MH', dialCode: '692'),
  CountryDial(name: 'Martinique', iso2: 'MQ', dialCode: '596'),
  CountryDial(name: 'Mauritania', iso2: 'MR', dialCode: '222'),
  CountryDial(name: 'Mauritius', iso2: 'MU', dialCode: '230'),
  CountryDial(name: 'Mayotte', iso2: 'YT', dialCode: '262'),
  CountryDial(name: 'Mexico', iso2: 'MX', dialCode: '52'),
  CountryDial(name: 'Micronesia', iso2: 'FM', dialCode: '691'),
  CountryDial(name: 'Moldova', iso2: 'MD', dialCode: '373'),
  CountryDial(name: 'Monaco', iso2: 'MC', dialCode: '377'),
  CountryDial(name: 'Mongolia', iso2: 'MN', dialCode: '976'),
  CountryDial(name: 'Montenegro', iso2: 'ME', dialCode: '382'),
  CountryDial(name: 'Montserrat', iso2: 'MS', dialCode: '1664'),
  CountryDial(name: 'Morocco', iso2: 'MA', dialCode: '212', nationalNumberLength: [9]),
  CountryDial(name: 'Mozambique', iso2: 'MZ', dialCode: '258'),
  CountryDial(name: 'Myanmar', iso2: 'MM', dialCode: '95'),
  CountryDial(name: 'Namibia', iso2: 'NA', dialCode: '264'),
  CountryDial(name: 'Nauru', iso2: 'NR', dialCode: '674'),
  CountryDial(name: 'Nepal', iso2: 'NP', dialCode: '977'),
  CountryDial(name: 'Netherlands', iso2: 'NL', dialCode: '31', nationalNumberLength: [9]),
  CountryDial(name: 'New Caledonia', iso2: 'NC', dialCode: '687'),
  CountryDial(name: 'New Zealand', iso2: 'NZ', dialCode: '64'),
  CountryDial(name: 'Nicaragua', iso2: 'NI', dialCode: '505'),
  CountryDial(name: 'Niger', iso2: 'NE', dialCode: '227'),
  CountryDial(name: 'Niue', iso2: 'NU', dialCode: '683'),
  CountryDial(name: 'North Korea', iso2: 'KP', dialCode: '850'),
  CountryDial(name: 'North Macedonia', iso2: 'MK', dialCode: '389'),
  CountryDial(name: 'Northern Mariana Islands', iso2: 'MP', dialCode: '1670'),
  CountryDial(name: 'Norway', iso2: 'NO', dialCode: '47'),
  CountryDial(name: 'Oman', iso2: 'OM', dialCode: '968'),
  CountryDial(name: 'Pakistan', iso2: 'PK', dialCode: '92'),
  CountryDial(name: 'Palau', iso2: 'PW', dialCode: '680'),
  CountryDial(name: 'Palestine', iso2: 'PS', dialCode: '970'),
  CountryDial(name: 'Panama', iso2: 'PA', dialCode: '507'),
  CountryDial(name: 'Papua New Guinea', iso2: 'PG', dialCode: '675'),
  CountryDial(name: 'Paraguay', iso2: 'PY', dialCode: '595'),
  CountryDial(name: 'Peru', iso2: 'PE', dialCode: '51'),
  CountryDial(name: 'Philippines', iso2: 'PH', dialCode: '63'),
  CountryDial(name: 'Poland', iso2: 'PL', dialCode: '48'),
  CountryDial(name: 'Portugal', iso2: 'PT', dialCode: '351'),
  CountryDial(name: 'Puerto Rico', iso2: 'PR', dialCode: '1787'),
  CountryDial(name: 'Qatar', iso2: 'QA', dialCode: '974'),
  CountryDial(name: 'Réunion', iso2: 'RE', dialCode: '262'),
  CountryDial(name: 'Romania', iso2: 'RO', dialCode: '40'),
  CountryDial(name: 'Russia', iso2: 'RU', dialCode: '7'),
  CountryDial(name: 'Rwanda', iso2: 'RW', dialCode: '250', nationalNumberLength: [9]),
  CountryDial(name: 'Saint Barthélemy', iso2: 'BL', dialCode: '590'),
  CountryDial(name: 'Saint Helena', iso2: 'SH', dialCode: '290'),
  CountryDial(name: 'Saint Kitts and Nevis', iso2: 'KN', dialCode: '1869'),
  CountryDial(name: 'Saint Lucia', iso2: 'LC', dialCode: '1758'),
  CountryDial(name: 'Saint Martin', iso2: 'MF', dialCode: '590'),
  CountryDial(name: 'Saint Pierre and Miquelon', iso2: 'PM', dialCode: '508'),
  CountryDial(name: 'Saint Vincent and the Grenadines', iso2: 'VC', dialCode: '1784'),
  CountryDial(name: 'Samoa', iso2: 'WS', dialCode: '685'),
  CountryDial(name: 'San Marino', iso2: 'SM', dialCode: '378'),
  CountryDial(name: 'São Tomé and Príncipe', iso2: 'ST', dialCode: '239'),
  CountryDial(name: 'Saudi Arabia', iso2: 'SA', dialCode: '966'),
  CountryDial(name: 'Senegal', iso2: 'SN', dialCode: '221'),
  CountryDial(name: 'Serbia', iso2: 'RS', dialCode: '381'),
  CountryDial(name: 'Seychelles', iso2: 'SC', dialCode: '248'),
  CountryDial(name: 'Sierra Leone', iso2: 'SL', dialCode: '232'),
  CountryDial(name: 'Singapore', iso2: 'SG', dialCode: '65'),
  CountryDial(name: 'Sint Maarten', iso2: 'SX', dialCode: '1721'),
  CountryDial(name: 'Slovakia', iso2: 'SK', dialCode: '421'),
  CountryDial(name: 'Slovenia', iso2: 'SI', dialCode: '386'),
  CountryDial(name: 'Solomon Islands', iso2: 'SB', dialCode: '677'),
  CountryDial(name: 'Somalia', iso2: 'SO', dialCode: '252'),
  CountryDial(name: 'South Africa', iso2: 'ZA', dialCode: '27', nationalNumberLength: [9]),
  CountryDial(name: 'South Korea', iso2: 'KR', dialCode: '82'),
  CountryDial(name: 'South Sudan', iso2: 'SS', dialCode: '211'),
  CountryDial(name: 'Spain', iso2: 'ES', dialCode: '34'),
  CountryDial(name: 'Sri Lanka', iso2: 'LK', dialCode: '94'),
  CountryDial(name: 'Sudan', iso2: 'SD', dialCode: '249'),
  CountryDial(name: 'Suriname', iso2: 'SR', dialCode: '597'),
  CountryDial(name: 'Sweden', iso2: 'SE', dialCode: '46'),
  CountryDial(name: 'Switzerland', iso2: 'CH', dialCode: '41'),
  CountryDial(name: 'Syria', iso2: 'SY', dialCode: '963'),
  CountryDial(name: 'Taiwan', iso2: 'TW', dialCode: '886'),
  CountryDial(name: 'Tajikistan', iso2: 'TJ', dialCode: '992'),
  CountryDial(name: 'Tanzania', iso2: 'TZ', dialCode: '255', nationalNumberLength: [9]),
  CountryDial(name: 'Thailand', iso2: 'TH', dialCode: '66'),
  CountryDial(name: 'Timor-Leste', iso2: 'TL', dialCode: '670'),
  CountryDial(name: 'Togo', iso2: 'TG', dialCode: '228'),
  CountryDial(name: 'Tokelau', iso2: 'TK', dialCode: '690'),
  CountryDial(name: 'Tonga', iso2: 'TO', dialCode: '676'),
  CountryDial(name: 'Trinidad and Tobago', iso2: 'TT', dialCode: '1868'),
  CountryDial(name: 'Tunisia', iso2: 'TN', dialCode: '216'),
  CountryDial(name: 'Turkey', iso2: 'TR', dialCode: '90'),
  CountryDial(name: 'Turkmenistan', iso2: 'TM', dialCode: '993'),
  CountryDial(name: 'Turks and Caicos Islands', iso2: 'TC', dialCode: '1649'),
  CountryDial(name: 'Tuvalu', iso2: 'TV', dialCode: '688'),
  CountryDial(name: 'Uganda', iso2: 'UG', dialCode: '256', nationalNumberLength: [9]),
  CountryDial(name: 'Ukraine', iso2: 'UA', dialCode: '380'),
  CountryDial(name: 'United Arab Emirates', iso2: 'AE', dialCode: '971', nationalNumberLength: [9]),
  CountryDial(name: 'United Kingdom', iso2: 'GB', dialCode: '44', nationalNumberLength: [10]),
  CountryDial(name: 'United States', iso2: 'US', dialCode: '1', nationalNumberLength: [10]),
  CountryDial(name: 'United States Virgin Islands', iso2: 'VI', dialCode: '1340'),
  CountryDial(name: 'Uruguay', iso2: 'UY', dialCode: '598'),
  CountryDial(name: 'Uzbekistan', iso2: 'UZ', dialCode: '998'),
  CountryDial(name: 'Vanuatu', iso2: 'VU', dialCode: '678'),
  CountryDial(name: 'Vatican City', iso2: 'VA', dialCode: '379'),
  CountryDial(name: 'Venezuela', iso2: 'VE', dialCode: '58'),
  CountryDial(name: 'Vietnam', iso2: 'VN', dialCode: '84'),
  CountryDial(name: 'Wallis and Futuna', iso2: 'WF', dialCode: '681'),
  CountryDial(name: 'Yemen', iso2: 'YE', dialCode: '967'),
  CountryDial(name: 'Zambia', iso2: 'ZM', dialCode: '260'),
  CountryDial(name: 'Zimbabwe', iso2: 'ZW', dialCode: '263'),
];
